### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by levithomason** [cvan/keyboardevent-key-polyfill#8]
The demo link in the readme is not up: https://cvan.io/keyboardevent-key-polyfill/

Why not update and use the [`gh-pages`](http://cvan.io/keyboardevent-key-polyfill/) version?

**Comment by levithomason** [comment]
I've opened a PR to update the demo as well #9

**Comment by cvan** [comment]
sorry, just now seeing this. not sure what the problem was at the time. it's up now: https://cvan.io/keyboardevent-key-polyfill/

btw, I just deleted the `gh-branches` branch and am publishing to GitHub Pages from `master` now.

thanks!
